lang: Rust
global:
  output_dir: ''
  template_dir: ./templates/rust/*
  file_override: true
  active_record: false
  open: false
  author: ''
  service_name: ''
  entity_name: ''
  service_impl_name: ''
  mapper_name: ''
  controller_name: ''
package:
  parent: com.snack
  module_name: ''
  entity: entity
  request: request
  response: response
  service: service
  service_impl: service.impl
  mapper: mapper
  controller: controller
  path_info: {}
strategy:
  capital_mode: false
  naming: UnderlineToCamel
  column_naming: NoChange
  entity_boolean_column_remove_is_prefix: false
  rest_controller_style: false
  entity_table_field_annotation_enable: false
  table_prefix: []
  field_prefix: []
  include: ["sys_post", "sys_user_post"]
  exclude: []
  skip_view: false
  table_fill_list: []
  name_convert: null
datasource:
  driver_name: 'com.mysql.cj.jdbc.Driver'
  username: 'root'
  password: 'MIMAlongchen520'
  url: 'mysql://rm-uf678lk3e0ze6bn482o.mysql.rds.aliyuncs.com:3306/snack_upms'
  db_type: Mysql
template:
  entity: ./templates/entity.rs
  service: ./templates/service.rs
  request: ./templates/request.rs
  response: ./templates/response.rs
  service_impl:
  controller: ./templates/controller.rs
  mapper: ./templates/mapper.rs
plugins: []
